// <auto-generated />
using System;
using FilesBrowser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilesBrowser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("FilesBrowser.Models.Folder", b =>
                {
                    b.Property<Guid>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            FolderId = new Guid("80ec3e83-ed43-4162-a4b1-39b2e766742c"),
                            Name = "Music"
                        },
                        new
                        {
                            FolderId = new Guid("9eb64af5-974f-4c8a-8696-a62920dbb56a"),
                            Name = "Images"
                        },
                        new
                        {
                            FolderId = new Guid("508cffbd-ce0d-4106-8429-bc9103924e05"),
                            Name = "GymPlalist",
                            ParentFolderId = new Guid("80ec3e83-ed43-4162-a4b1-39b2e766742c")
                        },
                        new
                        {
                            FolderId = new Guid("3b802dd0-e597-4f8b-99b4-66c134a3ef9f"),
                            Name = "WhiteGirlMusic",
                            ParentFolderId = new Guid("80ec3e83-ed43-4162-a4b1-39b2e766742c")
                        },
                        new
                        {
                            FolderId = new Guid("ccd9ba81-1b92-4a15-bf6e-3f1f1e48b3d0"),
                            Name = "MyMomPhotos",
                            ParentFolderId = new Guid("9eb64af5-974f-4c8a-8696-a62920dbb56a")
                        },
                        new
                        {
                            FolderId = new Guid("370a1e80-714e-4fbd-acfa-1fa2f6fb5875"),
                            Name = "MyDadPhotos",
                            ParentFolderId = new Guid("9eb64af5-974f-4c8a-8696-a62920dbb56a")
                        });
                });

            modelBuilder.Entity("FilesBrowser.Models.Folder", b =>
                {
                    b.HasOne("FilesBrowser.Models.Folder", "ParentFolder")
                        .WithMany("Subfolders")
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("FilesBrowser.Models.Folder", b =>
                {
                    b.Navigation("Subfolders");
                });
#pragma warning restore 612, 618
        }
    }
}
